
export const beneficiariesFields = {
  ASSOCIATION: "20",
  LAST_NAME: "2",
  FIRST_NAME: "1",
  WATER_SUPPLY:"21",
  PROVINCE:"14",
  DISTRICT:"15",
  LOCALITY:"17",
  ADMIN_POST:"16"
}


export const waterSupplyFields = {
  NAME: "121",
  LOCATION: "194",
  PROVINCE: "189",
  DISTRICT: "190",
  ADMIN_POST: "191",
  LOCALITY: "192",
  COMMUMITY: "193",
  AREA: "124",
  IRRABLE_AREA: "124",
  BEGIN_AT: '198',
  CO_SIGNED_AT: '156',
  CURRENT_EXECUTION:"",
  CURRENT_FASE:"",
  DELIVERY_AT:"199",
  ENTITY_NAME:"205",
  EXPECTED_EXCECUTION:"180",
  FEMALE_BENEFICIARIES:"219",
  FISCAL_CONTACT_NAME:"",
  FISCAL_CONTACT_TELEPHONE:"",
  HIRED_CONTACT_NAME:"",
  HIRED_CONTACT_TELEPHONE:"",
  LAST_MONITORED_AT:"",
  MALE_BENEFICIARIES:"218",
  PROGRESS:"",
  TEMPORARY_DELEVERY_AT:"",
  TIME_FRAME:"",
  TOTAL_BENEFICIARIES:"",

}